name: Ottimizza immagini
author: FrancescoRosi
inputs:
  libwebp-version:
    required: true
  directory:
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Installa Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Installa cwebp e svgo
      shell: bash
      run: |
        rm -rf $HOME/libwebp
        mkdir $HOME/libwebp
        wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${{ inputs.libwebp-version }}-linux-x86-64.tar.gz -O $HOME/libwebp.tar.gz
        tar -xf $HOME/libwebp.tar.gz -C $HOME/libwebp --strip-components=1
        echo "$HOME/libwebp/bin" >> $GITHUB_PATH
        sudo npm install svgo -g

    - name: Ottimizza immagini
      shell: bash
      run: |
        cd ${{ inputs.directory }}
        rm -rf optimized
        mkdir optimized
        touch optimized/.gitkeep
        for FILE in *.png; do 
          cwebp "$FILE" -resize 300 0 -o optimized/"${FILE%.*}".webp;
        done

        for FILE in *.svg; do
          svgo "$FILE" -o optimized/
        done

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Ottimizzazione immagini"
        file_pattern: "${{ inputs.directory }}/optimized/ ${{ inputs.directory }}/_ratios.json"
